[package]
name = "rust-webpack-multithreading"
version = "0.1.0"
publish = false
edition = "2018"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O4']

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"] }
